### ISSUE TITLE
Let users add process groups

### ISSUE THREAD

**Issue by fideloper** [fly-apps/fly-laravel#30]
There are 2 process groups that seem useful to add (for a total of 3 if running the app normally as well):

```toml
[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:work"
```
